//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theloaitin
    {
        public Theloaitin()
        {
            this.Tintucs = new HashSet<Tintuc>();
        }
    
        public int IDLoai { get; set; }
        public string Tentheloai { get; set; }
    
        public virtual ICollection<Tintuc> Tintucs { get; set; }
    }
}
