//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public TacGia()
        {
            this.VietSaches = new HashSet<VietSach>();
        }
    
        public int MaTG { get; set; }
        public string TenTG { get; set; }
        public string DiaChi { get; set; }
        public string TieuSu { get; set; }
        public Nullable<int> DienThoai { get; set; }
    
        public virtual ICollection<VietSach> VietSaches { get; set; }
    }
}
